service: pow-data-exporter
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:ap-northeast-1:#{AWS::AccountId}:function:pow-data-crawler-${self:provider.stage}
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - arn:aws:s3:::pow-data-csv-${self:provider.stage}/*
package: ${file(../../serverless.common.yml):package}
plugins:
  - serverless-pseudo-parameters
functions:
  exporter:
    handler: index.handler
    layers:
      - arn:aws:lambda:ap-northeast-1:#{AWS::AccountId}:layer:node_modules-for-pow-data-clawler:1
      - arn:aws:lambda:ap-northeast-1:172334698875:layer:axios:1
    name: ${self:service}-${self:provider.stage}
    description: クローラーを呼び出し、結果をS3に保存する
    runtime: nodejs12.x
    memorySize: 1024
    timeout: 30
    events:
      - schedule: cron(30 23 * * ? *)
    environment:
      CRAWLER_FUNCTION_NAME: ${file(../crawler/serverless.yml):service}-${self:provider.stage}
      S3_BUCKET_NAME: pow-data-csv-${self:provider.stage}
      SLACK_WEBHOOK_URL: ${file(./env.yml):slack_webhook_url}
      STAGE: ${self:provider.stage}
